# Generated by Django 5.0.3 on 2024-04-30 12:57

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_product_options_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=webapp.models.user_directory_path),
        ),
    ]
